language: c

sudo: required
env:
  global:
    - LUAROCKS=3.0.3
  matrix:
    - LUA=lua5.1
    - LUA=lua5.1 SSL=openssl-1.0.2p
    - LUA=lua5.2 SSL=libressl-2.8.0
    - LUA=lua5.3 SSL=openssl-1.1.1
    - LUA=luajit SSL=openssl-1.1.0i
    - LUA=luajit2.1
os:
  - linux
  - osx

matrix:
  allow_failures:
    - env: LUA=lua5.2 SSL=libressl-2.8.0

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh
  - bash .travis/setup_uv.sh
  - bash .travis/setup_ssl.sh
  - git submodule update --init --recursive
  - git submodule update --recursive

install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" && -z "$SSL" ]]; then sudo $HOME/.usr/bin/luarocks make openssl-scm-7.rockspec OPENSSL_DIR=/usr/local/opt/openssl; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" && -n "$SSL" ]]; then sudo $HOME/.usr/bin/luarocks make openssl-scm-7.rockspec OPENSSL_DIR=$HOME/.usr; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" && -z "$SSL" ]]; then sudo -H $HOME/.usr/bin/luarocks make openssl-scm-7.rockspec OPENSSL_DIR=/usr; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" && -n "$SSL" ]]; then sudo -H $HOME/.usr/bin/luarocks make openssl-scm-7.rockspec OPENSSL_DIR=$HOME/.usr; fi'

script:
  - cd test
  - curl https://raw.githubusercontent.com/bluebird75/luaunit/master/luaunit.lua > luaunit.lua
  - lua -e "package.cpath='../?.so'" test.lua

notifications:
  email:
    on_success: change
    on_failure: always
