language: c

dist: bionic

env:
  global:
    - LUAROCKS=3.3.1
  matrix:
    - LUA=lua5.1
    - LUA=lua5.1 SSL=openssl-1.0.2u
    - LUA=luajit2.1 SSL=openssl-1.0.2u
    - LUA=lua5.2 SSL=libressl-3.2.3
    - LUA=lua5.3 SSL=openssl-1.1.1j
    - LUA=lua5.4 SSL=openssl-1.1.1j
    - LUA=luajit SSL=openssl-1.1.0l
    - LUA=luajit2.1
os:
  - linux
  - osx

matrix:
  allow_failures:
    #    - env: LUA=lua5.2 SSL=libressl-2.8.3
    #branches:
    #  only:
    #    - master

before_install:
  - source .travis/setenv_lua.sh
  - bash .travis/setup_uv.sh
  - bash .travis/setup_ssl.sh
  - git submodule update --init --recursive
  - git submodule update --recursive

install:
  - bash .travis/install.sh

script:
  - cd test
  - LD_LIBRARY_PATH=$HOME/.usr/lib $HOME/.usr/bin/lua -e "package.cpath='../?.so'" test.lua
  - if [[ "$PLATFORM" == "linux" && "$SSL" =~ ^libressl ]]; then LD_LIBRARY_PATH=$HOME/.usr/lib valgrind --trace-children=yes -v --tool=memcheck --leak-check=full --track-origins=yes --leak-resolution=high --show-reachable=yes lua -e "package.cpath='../?.so'" test.lua; fi
  - cd ..

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && -z "$SSL" ]]; then coveralls --exclude deps --gcov-options '\-lp'; fi

before_deploy:
  - bash .travis/make_rockspec.sh $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: openssl-$TRAVIS_TAG.tar.gz
  cleanup: false
  on:
    tags: true
    branch: master
    condition: "$LUA == lua5.1 && $TRAVIS_OS_NAME == linux && -z $SSL"

after_deploy:
  - $HOME/.usr/bin/luarocks install lua-cjson # required for luarocks upload
  - $HOME/.usr/bin/luarocks upload openssl-$TRAVIS_TAG.rockspec --api-key=${LUAROCKS_TOKEN} --force
  - $HOME/.usr/bin/luarocks install openssl

notifications:
  email:
    on_success: change
    on_failure: always
